### ISSUE TITLE
 Support more than one instrument

### ISSUE THREAD

**Issue by cyclekiller** [liebharc/homr#7]
Some music such as symphonies has multiple tracks, every row is a track/instrument, for example
![图片](https://github.com/user-attachments/assets/fa40f74d-baf3-4153-8a7f-5275fefe9064)
Could you write some logic that separates each track and handles them one by one?
Currently the logic is closely coupled with single-instrument music (e.g. piano music). Thank you very much!

**Comment by liebharc** [comment]
Hello @cyclekiller ,

Interesting! `homr` was originally designed to convert sheet music for beginners, so this is pushing its limits. Let's break down what's needed to handle your case.

> Currently the logic is closely coupled with single-instrument music (e.g. piano music).

First, for context: `homr` already supports multiple instruments. In fact, piano is treated as two independent voices/instruments (though taking into account that it's one instrument with a broader range could improve detection—another topic entirely). The algorithm detects each staff individually and then identifies braces (brace_dot_detection.py). When it finds staffs grouped by a brace, it combines them. The code calls this "MultiStaff" because I couldn't find a widely accepted term for parallel staff systems. Polyphony can mean different things depending on cultural context https://github.com/NetEase/Polyphonic-TrOMR/issues/3#issuecomment-1829458959. 

Why it doesn’t work for your example: `homr` is designed for camera-captured images and uses filters to remove noise and artifacts. One filter eliminates large vertical black elements, which was added to remove page shadows. Unfortunately, this filter also removes the braces linking your staffs - simply because they are very big. We could adjust this filter (as done in https://github.com/liebharc/homr/tree/issue7bracefilter) to address that.

However, I’m unsure if this would fully solve your problem. `homr` has other limitations which might affect your use case - it only supports treble and bass clefs (G2 and F4 specifically) and lacks support for grace notes, triplets, slurs, and articulations. Adding these features, like additional clef support, could be as simple as training a new model if someone would volunteer on spending a couple of days doing this with their GPU. But that's more of a side note.

The question is: would adjusting the filter to detect the correct number of instruments be enough for your case, despite these limitations? If not, it may be best to keep the code as is since the filter works well in other scenarios. Feel free to experiment with the https://github.com/liebharc/homr/tree/issue7bracefilter branch to see if it meets your needs.

![beethoven-1](https://github.com/user-attachments/assets/b85abefe-490b-47dc-9286-73909c233eae)

**Comment by cyclekiller** [comment]
Okay, I understand where the issue came from. Thank you for your feedback.
My use case is to extract from the music sheets the basic "backbone" harmonic progressions, providing the visual annotations that which notes are part of the harmony and which ones are not (melody, etc.). So I just had to get a little help to do what I wanted to do. I'm not expecting it to do any tricky things. However, because the code base is complicated, I cannot get my head down to work at it.

**Comment by liebharc** [comment]
@cyclekiller , good to hear that this should be enough. I ran https://github.com/liebharc/homr/tree/issue7bracefilter on my test files and it looks okay. I still need to clean in up, before it can be merged. This might take some weeks, because I will be away for a bit.

> My use case is to extract from the music sheets the basic "backbone" harmonic progressions, given the visual annotations that which notes are part of the harmony and which ones are not (melody, etc.).

Sounds like a good project! If you publish something about it at some point, then I would be happy if you would let me know. Just because I'm curious about things :).

**Comment by cyclekiller** [comment]
@liebharc Hello, recently I published this paper [SymphonyGen: 3D Hierarchical Orchestral Generation with Controllable Harmony Skeleton](http://arxiv.org/abs/2604.25498), which involves my earlier idea of harmony backbones. I think you might be interested, although it is based on MIDI files rather than sheet music.

**Comment by liebharc** [comment]
Thanks. I added it to my reading list!
